import os
import sqlite3
import psycopg

SQLITE_DB = "hardware_inventory.db"


def get_database_url():
    url = os.getenv("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. In PowerShell, run: "
            '$env:DATABASE_URL="postgresql://postgres...."'
        )
    return url


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL DEFAULT 'user@campus.edu',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    is_locked INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS password_resets (
    request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    new_password_hash TEXT NOT NULL,
    request_time TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS hardware (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loans (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    item_id INTEGER NOT NULL,
    item_name TEXT NOT NULL,
    borrow_date TEXT NOT NULL,
    return_date TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'PENDING_BORROW'
        CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))
);
"""


def table_counts(cur):
    names = ["users", "password_resets", "hardware", "loans"]
    return {name: cur.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0] for name in names}


def migrate():
    if not os.path.exists(SQLITE_DB):
        raise FileNotFoundError(f"SQLite source database not found: {SQLITE_DB}")

    with sqlite3.connect(SQLITE_DB) as sqlite_conn:
        sqlite_conn.row_factory = sqlite3.Row
        sqlite_cur = sqlite_conn.cursor()
        sqlite_tables = {
            row[0] for row in sqlite_cur.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            )
        }

        required = {"users", "password_resets", "hardware", "loans"}
        missing = required - sqlite_tables
        if missing:
            raise RuntimeError(f"Missing SQLite tables: {', '.join(sorted(missing))}")

        users = [tuple(r) for r in sqlite_cur.execute("SELECT id, username, email, password_hash, role, failed_attempts, is_locked FROM users")]
        resets = [tuple(r) for r in sqlite_cur.execute("SELECT request_id, username, email, new_password_hash, request_time, status FROM password_resets")]
        hardware = [tuple(r) for r in sqlite_cur.execute("SELECT item_id, item_name, category, quantity, unit_price, status FROM hardware")]

        loan_columns = {r[1] for r in sqlite_cur.execute("PRAGMA table_info(loans)")}
        if "quantity" in loan_columns:
            loans = [tuple(r) for r in sqlite_cur.execute("SELECT loan_id, username, item_id, item_name, borrow_date, return_date, quantity, status FROM loans")]
        else:
            loans = [(*tuple(r), 1) for r in sqlite_cur.execute("SELECT loan_id, username, item_id, item_name, borrow_date, return_date, status FROM loans")]

    print("Connecting to Supabase PostgreSQL...")
    with psycopg.connect(get_database_url()) as pg_conn:
        with pg_conn.cursor() as cur:
            cur.execute(POSTGRES_SCHEMA)
            counts = table_counts(cur)
            if any(counts.values()):
                raise RuntimeError(
                    "The Supabase tables already contain data. Migration stopped to avoid duplicates. "
                    "Use a new/empty Supabase project or clear the four tables first."
                )

            if users:
                cur.executemany(
                    "INSERT INTO users (id, username, email, password_hash, role, failed_attempts, is_locked) VALUES (%s,%s,%s,%s,%s,%s,%s)",
                    users,
                )
            if resets:
                cur.executemany(
                    "INSERT INTO password_resets (request_id, username, email, new_password_hash, request_time, status) VALUES (%s,%s,%s,%s,%s,%s)",
                    resets,
                )
            if hardware:
                cur.executemany(
                    "INSERT INTO hardware (item_id, item_name, category, quantity, unit_price, status) VALUES (%s,%s,%s,%s,%s,%s)",
                    hardware,
                )
            if loans:
                cur.executemany(
                    "INSERT INTO loans (loan_id, username, item_id, item_name, borrow_date, return_date, quantity, status) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)",
                    loans,
                )

            # Make future generated IDs continue after the migrated IDs.
            for table, pk in [("users", "id"), ("password_resets", "request_id"), ("hardware", "item_id"), ("loans", "loan_id")]:
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence('{table}', '{pk}'), COALESCE((SELECT MAX({pk}) FROM {table}), 1), true)"
                )

        pg_conn.commit()

    print("\nMigration completed successfully.")
    print(f"  users:            {len(users)}")
    print(f"  password_resets:  {len(resets)}")
    print(f"  hardware:         {len(hardware)}")
    print(f"  loans:            {len(loans)}")


if __name__ == "__main__":
    migrate()
